from datetime import datetime, timedelta, timezone
from decimal import Decimal, ROUND_HALF_UP

import razorpay

from app.core.config import get_settings


def normalize_currency(
    currency,
) -> str:
    """
    Normalize ClickHouse FixedString, bytes and normal
    string currency values into a Razorpay code.
    """

    if isinstance(
        currency,
        (bytes, bytearray, memoryview),
    ):
        currency = bytes(currency).decode(
            "utf-8"
        )

    normalized_currency = (
        str(currency)
        .replace("\x00", "")
        .strip()
        .upper()
    )

    return normalized_currency


def get_razorpay_client():
    """
    Create and return the configured Razorpay client.
    """

    settings = get_settings()

    if not settings.razorpay_key_id:
        raise RuntimeError(
            "RAZORPAY_KEY_ID is not configured"
        )

    if not settings.razorpay_key_secret:
        raise RuntimeError(
            "RAZORPAY_KEY_SECRET is not configured"
        )

    return razorpay.Client(
        auth=(
            settings.razorpay_key_id,
            settings.razorpay_key_secret,
        )
    )


def verify_webhook_signature(
    payload: bytes | str = b"",
    signature: str = "",
    **kwargs,
) -> bool:
    """
    Verify that an incoming webhook was genuinely
    sent by Razorpay.

    Additional keyword handling keeps this compatible
    with route code using names such as raw_body,
    webhook_body or webhook_signature.
    """

    payload = (
        kwargs.get("raw_body")
        or kwargs.get("webhook_body")
        or kwargs.get("body")
        or payload
    )

    signature = (
        kwargs.get("webhook_signature")
        or kwargs.get("received_signature")
        or signature
    )

    if not payload:
        raise ValueError(
            "Razorpay webhook payload is missing"
        )

    if not signature:
        raise ValueError(
            "Razorpay webhook signature is missing"
        )

    settings = get_settings()

    webhook_secret = (
        settings.razorpay_webhook_secret
    )

    if not webhook_secret:
        raise RuntimeError(
            "RAZORPAY_WEBHOOK_SECRET is not configured"
        )

    if isinstance(payload, bytes):
        payload = payload.decode("utf-8")

    client = get_razorpay_client()

    client.utility.verify_webhook_signature(
        payload,
        signature,
        webhook_secret,
    )

    return True


def is_demo_email(
    email: str,
) -> bool:
    """
    Identify demonstration addresses that must not
    receive real notifications.
    """

    normalized_email = email.strip().lower()

    return normalized_email.endswith(
        (
            "@example.com",
            "@example.demo",
        )
    )


def is_demo_phone(
    phone: str,
) -> bool:
    """
    Demo phones generated by StudioPay begin with
    +910. They must never receive SMS notifications.
    """

    return phone.strip().startswith("+910")


def create_payment_link(
    payment: dict,
) -> dict:
    """
    Create a Razorpay Payment Link for an eligible
    StudioPay recovery payment.
    """

    settings = get_settings()

    # Protect the hackathon application from
    # accidentally creating Live Mode payment links.
    if not settings.razorpay_key_id.startswith(
        "rzp_test_"
    ):
        raise RuntimeError(
            "StudioPay currently supports Razorpay "
            "Test Mode only"
        )

    client = get_razorpay_client()

    amount = Decimal(
        str(payment["amount"])
    )

    if amount <= 0:
        raise ValueError(
            "Payment amount must be greater than zero"
        )

    amount_paise = int(
        (
            amount * Decimal("100")
        ).quantize(
            Decimal("1"),
            rounding=ROUND_HALF_UP,
        )
    )

    currency = normalize_currency(
        payment.get("currency", "INR")
    )

    if len(currency) != 3:
        raise ValueError(
            "Invalid payment currency"
        )

    customer_name = str(
        payment.get("customer_name", "")
    ).strip()

    customer_email = str(
        payment.get("customer_email", "")
    ).strip()

    customer_phone = str(
        payment.get("customer_phone", "")
    ).strip()

    if not customer_name:
        raise ValueError(
            "Customer name is required"
        )

    demo_email = is_demo_email(
        customer_email
    )

    demo_phone = is_demo_phone(
        customer_phone
    )

    customer = {
        "name": customer_name,
    }

    if customer_email:
        customer["email"] = customer_email

    # Do not pass generated demo numbers to Razorpay.
    if customer_phone and not demo_phone:
        customer["contact"] = customer_phone

    notify_email = bool(
        customer_email
        and not demo_email
    )

    notify_sms = bool(
        customer_phone
        and not demo_phone
    )

    expires_at = (
        datetime.now(timezone.utc)
        + timedelta(days=7)
    )

    request_data = {
        "amount": amount_paise,
        "currency": currency,
        "accept_partial": False,
        "description": (
            "StudioPay recovery for "
            f'{payment["invoice_id"]}'
        ),
        "reference_id": payment["invoice_id"],
        "customer": customer,
        "notify": {
            "sms": notify_sms,
            "email": notify_email,
        },
        "reminder_enable": bool(
            notify_sms or notify_email
        ),
        "expire_by": int(
            expires_at.timestamp()
        ),
        "notes": {
            "studiopay_payment_id": str(
                payment["payment_id"]
            ),
            "failure_code": str(
                payment.get(
                    "failure_code",
                    "",
                )
            ),
            "environment": "test",
        },
    }

    response = client.payment_link.create(
        request_data
    )

    return {
        "razorpay_link_id": response["id"],
        "short_url": response["short_url"],
        "status": response["status"],
        "amount": float(amount),
        "currency": currency,
        "reference_id": payment["invoice_id"],
        "expire_by": response.get("expire_by"),
        "customer_email": customer_email,
        "customer_phone": customer_phone,
        "email_notification_requested": (
            notify_email
        ),
        "sms_notification_requested": (
            notify_sms
        ),
        "test_mode": True,
    }